# Server Configuration
server.port=8080
# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_management_system}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=postgres
spring.datasource.password=admin@123
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Transaction Settings
spring.jpa.properties.hibernate.connection.autocommit=false
# Connection Pool Settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
# Logging Configurations
logging.level.org.springframework=INFO
logging.level.com.ems.mis=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ukwishakasandrine51@gmail.com
spring.mail.password=skvziaauiggxjfia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
jwt.secret=mySuperSecretKeyForJWTTokenGeneration12345678901234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000