apiVersion: v1
kind: Secret
metadata:
  name: ems-db-secret
type: Opaque
# You can either apply this file after replacing placeholders, or create the secret with kubectl create secret generic
stringData:
  username: "<DB_USER>"
  password: "<DB_PASSWORD>"
